defaults: &defaults
  twitter:
    api_key: "YaZGDJ0PI5VSfofWlkO4Dlike"
    api_secret: "yfCKHYBKoaTJAHkIdKWgGUjwxxEoCoyMuIqcplQh3mw8ZpOMoy"
  facebook:
    api_key: "644268655657579"
    api_secret: "23f3a45cc09a634c872aae6ab4e80213"
  linkedin:
    api_key: "75srgca9mj77pg"
    api_secret: "9D11KhoJaO8dNexz"
  google_oauth2:
    api_key: "952659476018-mlegr3nl6pm6lmk24bcg5m2opajhn8h0.apps.googleusercontent.com"
    api_secret: "s-yNXWcUr_Zzl2D-M74OGKtJ"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  twitter:
    api_key: "1D0tftEGPYEYDkAdDw6gW18U6"
    api_secret: "3UmXOmQMwAFKjAaDGkjsBNPmQN9TbWXq0HQOekidWDjU8chr4K"
  facebook:
    api_key: "742725949083582"
    api_secret: "9c7dc7e878843500f1fd79ae1a3441b0"  
  linkedin:
    api_key: "756adigae1cadc"
    api_secret: "bGnjKZEXVY1lvmtO"
  google_oauth2:
    api_key: "500243699425-e0ccjin1dh65dalrgf594fejddf6qt81.apps.googleusercontent.com"
    api_secret: "QRmKHbwAa8_kFIyCO1E1xgI2"